version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /home/tom/PhpstormProjects/host/web:/usr/share/nginx/html
      - /home/tom/PhpstormProjects/host/docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
  php:
    image: php:fpm
    volumes:
      - /home/tom/PhpstormProjects/host/web:/usr/share/nginx/html
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
  node:
    build: .
    volumes:
      - /home/tom/PhpstormProjects/host/web:/usr/src/app
    ports:
      - "3000:3000"
